from django.urls import path

from .views import (
    UserLoginView,
    UserLogoutView,
    UserPasswordResetCompleteView,
    UserPasswordResetConfirmView,
    UserPasswordResetDoneView,
    UserPasswordResetView,
    activate_account_view,
    activate_child_account_view,
    achievements_view,
    analysis_view,
    dashboard_view,
    home_view,
    mobile_login_api_view,
    mobile_preferences_api_view,
    mobile_signup_api_view,
    mobile_summary_api_view,
    peer_sleep_view,
    profile_view,
    sync_sources_view,
    signup_done_view,
    signup_view,
)

urlpatterns = [
    path("", home_view, name="home"),
    path("rejestracja/", signup_view, name="signup"),
    path("rejestracja/sukces/", signup_done_view, name="signup_done"),
    path("logowanie/", UserLoginView.as_view(), name="login"),
    path("wylogowanie/", UserLogoutView.as_view(), name="logout"),
    path("profil/", profile_view, name="profile"),
    path("profil/zrodla-danych/", sync_sources_view, name="sync_sources"),
    path("api/mobile/login/", mobile_login_api_view, name="mobile_login_api"),
    path("api/mobile/signup/", mobile_signup_api_view, name="mobile_signup_api"),
    path("api/mobile/preferences/", mobile_preferences_api_view, name="mobile_preferences_api"),
    path("api/mobile/summary/", mobile_summary_api_view, name="mobile_summary_api"),
    path("osiagniecia/", achievements_view, name="achievements"),
    path("dashboard/", dashboard_view, name="dashboard"),
    path("analiza-snu/", analysis_view, name="sleep_analysis"),
    path("sen-w-grupie/", peer_sleep_view, name="peer_sleep"),
    path(
        "reset-hasla/",
        UserPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "reset-hasla/wyslano/",
        UserPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset-hasla/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset-hasla/gotowe/",
        UserPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(
        "aktywacja/<uidb64>/<token>/",
        activate_account_view,
        name="activate_account",
    ),
    path(
        "zgoda-rodzica/<uidb64>/<token>/",
        activate_child_account_view,
        name="activate_child_account",
    ),
]
