# Generated by Django 6.0.3 on 2026-04-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_preferred_sync_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil użytkownika', 'verbose_name_plural': 'Profile użytkowników'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nazwa użytkownika'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lifestyle',
            field=models.CharField(blank=True, choices=[('sedentary', 'Tryb siedzący, znikoma aktywność'), ('moderate', 'Umiarkowana aktywność fizyczna'), ('physical_high', 'Praca fizyczna, duża aktywność')], max_length=20, verbose_name='Aktywność fizyczna'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sleep_goal_hours',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Docelowa długość snu'),
        ),
    ]
