# Generated by Django 6.0.3 on 2026-04-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_friendship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil uÅ¼ytkownika', 'verbose_name_plural': 'Profile uÅ¼ytkownikÃ³w'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='active_hypothesis',
            field=models.CharField(blank=True, choices=[('', 'Bez aktywnej hipotezy'), ('caffeine', 'Sprawdzam wpÅ‚yw kofeiny na sen'), ('stress', 'Sprawdzam wpÅ‚yw stresu na sen'), ('nap', 'Sprawdzam wpÅ‚yw drzemek na nocny sen'), ('alcohol', 'Sprawdzam wpÅ‚yw alkoholu na sen'), ('training', 'Sprawdzam wpÅ‚yw treningu na sen')], default='', max_length=20, verbose_name='Aktywna hipoteza miesiaca'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age_group',
            field=models.CharField(blank=True, choices=[('under_18', 'PoniÅ¼ej 18 lat'), ('18-25', '18-25 lat'), ('26-35', '26-35 lat'), ('36-50', '36-50 lat'), ('51+', '51+ lat')], max_length=10, verbose_name='Grupa wiekowa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(choices=[('moon', 'KsiÄ™Å¼yc'), ('star', 'Gwiazda'), ('cloud', 'Chmurka'), ('sun', 'SÅ‚oÅ„ce'), ('leaf', 'Listek'), ('heart', 'Serce')], default='moon', max_length=20, verbose_name='Awatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nazwa uÅ¼ytkownika'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lifestyle',
            field=models.CharField(blank=True, choices=[('sedentary', 'Tryb siedzÄ…cy, znikoma aktywnoÅ›Ä‡'), ('moderate', 'Umiarkowana aktywnoÅ›Ä‡ fizyczna'), ('physical_high', 'Praca fizyczna, duÅ¼a aktywnoÅ›Ä‡')], max_length=20, verbose_name='AktywnoÅ›Ä‡ fizyczna'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sleep_goal_hours',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Docelowa dÅ‚ugoÅ›Ä‡ snu'),
        ),
    ]
