# Generated by Django 6.0.3 on 2026-05-05 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_update_preferred_sync_source_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BugReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bug", "Błąd w aplikacji"),
                            ("data", "Problem z danymi snu"),
                            ("account", "Konto lub logowanie"),
                            ("idea", "Pomysł na usprawnienie"),
                            ("other", "Inne"),
                        ],
                        default="bug",
                        max_length=20,
                        verbose_name="Kategoria",
                    ),
                ),
                ("description", models.TextField(verbose_name="Opis problemu")),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="Przeglądarka"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nowe"),
                            ("reviewed", "Sprawdzone"),
                            ("resolved", "Rozwiązane"),
                        ],
                        default="new",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bug_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zgloszenie bledu",
                "verbose_name_plural": "Zgloszenia bledow",
                "ordering": ["-created_at"],
            },
        ),
    ]
