# Generated by Django 6.0.3 on 2026-05-05 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_bugreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("profile", "Profil"),
                            ("sleep", "Sen"),
                            ("sync", "Synchronizacja"),
                            ("support", "Pomoc"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="Typ",
                    ),
                ),
                ("title", models.CharField(max_length=140, verbose_name="Tytuł")),
                ("body", models.TextField(verbose_name="Treść")),
                (
                    "action_url",
                    models.CharField(blank=True, max_length=240, verbose_name="Adres akcji"),
                ),
                (
                    "dedupe_key",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Klucz deduplikacji",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Przeczytane")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data przeczytania",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Powiadomienie",
                "verbose_name_plural": "Powiadomienia",
                "ordering": ["-created_at"],
            },
        ),
    ]
