# Generated by Django 6.0.3 on 2026-05-06

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_clean_notification_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.user_avatar_upload_path,
                verbose_name="Zdjecie awatara",
            ),
        ),
    ]
