# Generated by Django 6.0.3 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_userprofile_avatar_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_image_data",
            field=models.TextField(blank=True, verbose_name="Dane zdjecia awatara"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_image_mime",
            field=models.CharField(blank=True, max_length=80, verbose_name="Typ zdjecia awatara"),
        ),
    ]
