# Generated by Django 6.0.3 on 2026-03-26 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual_csv', 'Import CSV'), ('mi_fitness', 'Mi Fitness'), ('zepp_life', 'Zepp Life')], max_length=20, verbose_name='Zrodlo')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nazwa pliku')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Data importu')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Wszystkie wiersze')),
                ('added_count', models.PositiveIntegerField(default=0, verbose_name='Dodane rekordy')),
                ('duplicate_count', models.PositiveIntegerField(default=0, verbose_name='Duplikaty')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Bledy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historia importu',
                'verbose_name_plural': 'Historia importow',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual_csv', 'Import CSV'), ('mi_fitness', 'Mi Fitness'), ('zepp_life', 'Zepp Life')], max_length=20, verbose_name='Zrodlo')),
                ('sleep_date', models.DateField(verbose_name='Data nocy')),
                ('sleep_duration_minutes', models.PositiveIntegerField(verbose_name='Czas snu (min)')),
                ('avg_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Srednie tetno')),
                ('min_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Minimalne tetno')),
                ('max_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maksymalne tetno')),
                ('min_spo2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Minimalne SpO2')),
                ('movement_level', models.CharField(choices=[('low', 'Niski'), ('medium', 'Sredni'), ('high', 'Wysoki'), ('unknown', 'Brak danych')], default='unknown', max_length=20, verbose_name='Ruch/aktywnosc')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Dane surowe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rekord snu',
                'verbose_name_plural': 'Rekordy snu',
                'ordering': ['-sleep_date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'source', 'sleep_date'), name='unique_sleep_record_per_source_and_date')],
            },
        ),
    ]
