# Generated by Django 6.0.3 on 2026-03-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0003_sleeprecord_bedtime_sleeprecord_wake_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importhistory',
            options={'ordering': ['-imported_at'], 'verbose_name': 'Historia importu', 'verbose_name_plural': 'Historia importów'},
        ),
        migrations.RemoveField(
            model_name='sleeprecord',
            name='max_heart_rate',
        ),
        migrations.RemoveField(
            model_name='sleeprecord',
            name='min_heart_rate',
        ),
        migrations.RemoveField(
            model_name='sleeprecord',
            name='movement_level',
        ),
        migrations.AddField(
            model_name='sleeprecord',
            name='awake_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Czas czuwania (min)'),
        ),
        migrations.AddField(
            model_name='sleeprecord',
            name='deep_sleep_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sen głęboki (min)'),
        ),
        migrations.AddField(
            model_name='sleeprecord',
            name='light_sleep_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sen lekki (min)'),
        ),
        migrations.AddField(
            model_name='sleeprecord',
            name='rem_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='REM (min)'),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='error_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Błędy'),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='source',
            field=models.CharField(choices=[('manual_csv', 'Import CSV'), ('mi_fitness', 'Import CSV'), ('zepp_life', 'Import CSV')], max_length=20, verbose_name='Źródło'),
        ),
        migrations.AlterField(
            model_name='sleepnote',
            name='sleep_quality',
            field=models.CharField(choices=[('bad', 'Słaba'), ('neutral', 'Neutralna'), ('good', 'Dobra')], default='neutral', max_length=10, verbose_name='Jakość snu'),
        ),
        migrations.AlterField(
            model_name='sleepnote',
            name='training_level',
            field=models.CharField(choices=[('none', 'Brak'), ('light', 'Lekki'), ('moderate', 'Średni'), ('hard', 'Ciężki')], default='none', max_length=10, verbose_name='Trening'),
        ),
        migrations.AlterField(
            model_name='sleeprecord',
            name='avg_heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Średnie tętno'),
        ),
        migrations.AlterField(
            model_name='sleeprecord',
            name='source',
            field=models.CharField(choices=[('manual_csv', 'Import CSV'), ('mi_fitness', 'Import CSV'), ('zepp_life', 'Import CSV')], max_length=20, verbose_name='Źródło'),
        ),
    ]
