# Generated by Django 6.0.3 on 2026-04-11 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0008_sleepnote_nap_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=80, unique=True, verbose_name='Klucz API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Ostatnie uÅ¼ycie')),
            ],
            options={
                'verbose_name': 'Token API synchronizacji',
                'verbose_name_plural': 'Tokeny API synchronizacji',
            },
        ),
        migrations.CreateModel(
            name='SleepSyncConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('health_connect', 'Health Connect'), ('zepp_sync', 'Zepp')], max_length=30, verbose_name='Dostawca synchronizacji')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Czy poÅ‚Ä…czenie jest aktywne')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Ostatnia synchronizacja')),
                ('last_imported_count', models.PositiveIntegerField(default=0, verbose_name='Liczba ostatnio pobranych rekordÃ³w')),
                ('last_error', models.TextField(blank=True, verbose_name='Ostatni bÅ‚Ä…d')),
                ('last_device_name', models.CharField(blank=True, max_length=120, verbose_name='Ostatnie urzÄ…dzenie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PoÅ‚Ä…czenie synchronizacji snu',
                'verbose_name_plural': 'PoÅ‚Ä…czenia synchronizacji snu',
                'ordering': ['provider'],
            },
        ),
        migrations.AlterModelOptions(
            name='importhistory',
            options={'ordering': ['-imported_at'], 'verbose_name': 'Historia importu', 'verbose_name_plural': 'Historie importów'},
        ),
        migrations.AddField(
            model_name='sleeprecord',
            name='device_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nazwa urzÄ…dzenia'),
        ),
        migrations.AddField(
            model_name='sleeprecord',
            name='external_record_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='ID zewnÄ™trznego rekordu'),
        ),
        migrations.AddField(
            model_name='sleeprecord',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data synchronizacji'),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='source',
            field=models.CharField(choices=[('manual_csv', 'Import CSV'), ('mi_fitness', 'Import CSV'), ('zepp_life', 'Import CSV'), ('health_connect', 'Health Connect'), ('zepp_sync', 'Synchronizacja Zepp')], max_length=20, verbose_name='Źródło'),
        ),
        migrations.AlterField(
            model_name='sleepnote',
            name='caffeine_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Liczba wypitych napojów z kofeiną'),
        ),
        migrations.AlterField(
            model_name='sleepnote',
            name='caffeine_last_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Godzina ostatniej dawki kofeiny'),
        ),
        migrations.AlterField(
            model_name='sleeprecord',
            name='source',
            field=models.CharField(choices=[('manual_csv', 'Import CSV'), ('mi_fitness', 'Import CSV'), ('zepp_life', 'Import CSV'), ('health_connect', 'Health Connect'), ('zepp_sync', 'Synchronizacja Zepp')], max_length=20, verbose_name='Źródło'),
        ),
        migrations.AddConstraint(
            model_name='sleeprecord',
            constraint=models.UniqueConstraint(condition=models.Q(('external_record_id', ''), _negated=True), fields=('user', 'source', 'external_record_id'), name='unique_external_sleep_record_per_source'),
        ),
        migrations.AddField(
            model_name='sleepapitoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_api_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sleepsyncconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_sync_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='sleepsyncconnection',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_sleep_sync_connection_per_provider'),
        ),
    ]
